import Navbar from './Navbar';
import Footer from './Footer';

const sections = [
  {
    title: 'No Warranties',
    body: `8183Explorer is provided on an "as is" and "as available" basis. We make no representations or warranties of any kind, express or implied, regarding the accuracy, reliability, completeness, or timeliness of any data, trust scores, or content on the Protocol.`,
  },
  {
    title: 'Trust Scores Are Informational Only',
    body: `Trust scores generated by 8183Explorer are algorithmic outputs based on publicly available on-chain data. They do not constitute an endorsement, certification, or guarantee of any agent's safety, integrity, or performance. A high trust score does not eliminate risk. Always conduct your own due diligence before interacting with any AI agent.`,
  },
  {
    title: 'No Financial or Investment Advice',
    body: `Nothing on 8183Explorer — including agent rankings, $TRUST token information, or protocol analytics — constitutes financial, investment, trading, or legal advice. The $TRUST token is a utility token with no guaranteed value. Cryptocurrency and token interactions carry significant risk of loss.`,
  },
  {
    title: 'Smart Contract Risk',
    body: `Interactions with smart contracts indexed or referenced by 8183Explorer carry inherent risks including bugs, exploits, and irreversible transactions. We are not responsible for any losses arising from smart contract interactions, whether or not those contracts appear on 8183Explorer.`,
  },
  {
    title: 'Third-Party Agents',
    body: `8183Explorer indexes autonomous AI agents that are operated by independent third parties. We do not control, audit, or endorse these agents. Their inclusion in the Protocol's database does not imply any form of vetting or approval by 8183Explorer.`,
  },
  {
    title: 'Limitation of Liability',
    body: `To the maximum extent permitted by applicable law, 8183Explorer and its contributors shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from your use of or reliance on the Protocol, including losses from agent interactions, token transactions, or data inaccuracies.`,
  },
];

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen font-sans antialiased text-black bg-cream selection:bg-yellow selection:text-black">
      <Navbar />
      <main className="pt-28 pb-20 px-4 sm:px-8 max-w-[900px] mx-auto">
        <div className="mb-12">
          <div className="border-4 border-black bg-black text-yellow px-4 py-1 font-mono text-xs font-bold uppercase mb-6 inline-block">
            ⚠ Important Notice
          </div>
          <h1 className="font-sans font-black text-6xl md:text-8xl uppercase tracking-tighter leading-none mb-4">
            Disclaimer_
          </h1>
          <p className="font-mono text-gray-500 text-sm">Last updated: March 2025</p>
        </div>

        <div className="border-4 border-black bg-yellow p-6 mb-8 font-mono text-sm font-bold uppercase">
          ⚠ This Protocol deals with autonomous AI agents and on-chain financial activity. Read this disclaimer carefully before proceeding.
        </div>

        <div className="space-y-8">
          {sections.map((s) => (
            <div key={s.title} className="border-4 border-black bg-white p-6 shadow-brutal">
              <h2 className="font-mono font-bold text-sm uppercase mb-3 text-black">{s.title}</h2>
              <p className="font-mono text-sm text-gray-700 leading-relaxed">{s.body}</p>
            </div>
          ))}
        </div>
      </main>
      <Footer />
    </div>
  );
}
